register hdfs:///packetpig/packetpig.jar
register hdfs:///packetpig/kraken-pcap-1.6.0.jar
register hdfs:///packetpig/piggybank.jar
register hdfs:///packetpig/commons-discovery-20040218.194635.jar
register hdfs:///packetpig/axis-1.4.jar
register hdfs:///packetpig/slf4j-api-1.6.4.jar
register hdfs:///packetpig/dnsjava-2.1.1.jar
register hdfs:///packetpig/mongo-2.9.0.jar
register hdfs:///packetpig/mongo-hadoop-core-1.1.0-SNAPSHOT.jar
register hdfs:///packetpig/mongo-hadoop-pig-1.1.0-SNAPSHOT.jar
