register lib/packetpig.jar
register lib/kraken-pcap-1.6.0.jar
register lib/piggybank.jar
register lib/commons-discovery-20040218.194635.jar
register lib/axis-1.4.jar
register lib/slf4j-api-1.6.4.jar
register lib/dnsjava-2.1.1.jar
register lib/mongo-2.9.0.jar
register lib/mongo-hadoop-core-1.1.0-SNAPSHOT.jar
register lib/mongo-hadoop-pig-1.1.0-SNAPSHOT.jar
