register s3://packetpig/packetpig.jar
register s3://packetpig/kraken-pcap-1.6.0.jar
register s3://packetpig/piggybank.jar
register s3://packetpig/commons-discovery-20040218.194635.jar
register s3://packetpig/axis-1.4.jar
register s3://packetpig/slf4j-api-1.6.4.jar
register s3://packetpig/dnsjava-2.1.1.jar
register s3://packetpig/mongo-2.9.0.jar
register s3://packetpig/mongo-hadoop-core-1.1.0-SNAPSHOT.jar
register s3://packetpig/mongo-hadoop-pig-1.1.0-SNAPSHOT.jar
